<?php

namespace Alm\ControlStockBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlmAdmProductoRepository extends EntityRepository
{
  public function findAjaxValue($term){
      $em = $this->getEntityManager();
      $term = str_replace(' ', '%', $term);
      $consul = $em->createQuery('SELECT p
                                  FROM AlmControlStockBundle:AlmAdmProducto p
                                  WHERE p.nombre LIKE \'%'.$term.'%\'
                               ');
      $resp = $consul->getResult();
      return $resp;
  }
}
