<?php 
namespace Alm\ControlStockBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductoLabRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LabAlmDetalleingresoRepository extends EntityRepository
{
	public function findByFechas($fecIni,$fecFin){
        $em=$this->getEntityManager();
                return $em->createQuery('
                SELECT d
                FROM AlmControlStockBundle:LabAlmDetalleingreso d join d.ingreso i
                WHERE i.creadoEl>:fecIni
                AND i.creadoEl<:fecFin
                AND i.estado=2
                ORDER BY d.productolab')
                ->setParameter('fecIni',$fecIni)
                ->setParameter('fecFin',$fecFin)
                ->getResult();
        
    }
}