<?php 
namespace Alm\ControlStockBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductoLabRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LabAlmDetalleegresoRepository extends EntityRepository
{
	public function findByFechas($fecIni,$fecFin){
        $em=$this->getEntityManager();
                return $em->createQuery('
                SELECT d
                FROM AlmControlStockBundle:LabAlmDetalleegreso d join d.egreso i
                WHERE i.creadoEl>:fecIni
                AND i.creadoEl<:fecFin
                AND i.estado=2
                ORDER BY d.productolab ASC')
                ->setParameter('fecIni',$fecIni)
                ->setParameter('fecFin',$fecFin)
                ->getResult();
        
    }
}